url = "https://<Managed environment>/api/v2/metrics/ingest"
header = "Authorization: Api-Token <API token>"
header = "Content-Type: text/plain; charset=utf-8"
insecure
silent
show-error
fail
connect-timeout = 15
max-time = 60
